### ISSUE TITLE
Complete lack of wine support 

### ISSUE THREAD

**Issue by ghost** [bisquad/DesktopController#1]
Tried to run this on Gentoo with Wine 2.3 and NOTHING! Will test on my Zune and report back with a new issue if that too fails to meet my expectations.

**Comment by ghost** [comment]
How do I load it onto my Zune 30?

**Comment by r-hackett** [comment]
Wait, you tried to run it with Wine and expected the desktop icons to move? Come on son. Zune is purposefully unsupported out of spite from now on.

**Comment by ghost** [comment]
You are a cruel tyrant, denormal. My zune was working just fine until the latest commit. I had hoped we could resolve this amicably but now you've forced me to create my own fork. Soon enough DesktopController2:ElectricBoogaloo will run on any device, always.
